### ISSUE TITLE
Follow Symlinks? 

### ISSUE THREAD

**Issue by Romans-I-XVI** [TwitchBronBron/roku-deploy#3]
Hi, so I use submodules that exist outside the channel directory that I need a couple files brought in from. Personally I feel like symlinks would be easiest to use however currently Roku-Deploy zips the actual symlink instead of following it.

Would it be easy to change this?

**Comment by TwitchBronBron** [comment]
I'm looking into symlink support. In the mean time, would something like this solve your use case?

**Comment by TwitchBronBron** [comment]
It looks like dereferencing the symlinks is a one-liner. 

[Here's a branch ](https://github.com/TwitchBronBron/roku-deploy/tree/feature/follow-symlinks) with this feature implemented. I tried some things on my machine but couldn't reproduce your issue (probably because it's on a windows machine and symlinks might work differently).

let me know if that works for you.

**Comment by Romans-I-XVI** [comment]
Yes, I knew I could also solve the problem using rootDir but just figured it'd be convenient if symlinks worked too. I'm very glad to see it was a simple thing to implement, I tested out the feature branch and it works wonderfully :)

**Comment by TwitchBronBron** [comment]
This is now enabled by default in release `2.0.0`
